name: Bats test
on:
  push:
    paths:
      - AliyunOpenApiSDK.sh
      - test/test.bats.sh
  pull_request:
    paths:
      - AliyunOpenApiSDK.sh
      - test/test.bats.sh

jobs:
  test:
    runs-on: ubuntu-18.04 # Test on old version bash
    steps:
    - name: Check out code
      uses: actions/checkout@v3
        with:
          submodules: true
    - name: Run test
      env:
        AliAccessKeyId: ${{ secrets.ALIACCESSKEYID }}
        AliAccessKeySecret: ${{ secrets.ALIACCESSKEYSECRET }}
        run: ./test/bats/bin/bats test/test.bats.sh
