name: Linter
on:
  push:
    paths:
      - '.github/workflows/linter.yml'
      - '**.sh'
  pull_request:
    paths:
      - '.github/workflows/linter.yml'
      - '**.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -x
        with:
          ignore_paths: ./test/bats/** ./test/test_helper/**
